name: yasin_tahlil
description: "A new Flutter project."
publish_to: 'none'
version: 1.3.0+9 # Naik versi lagi biar gampang updatenya

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # <--- INI TAMBAHANNYA AYANK
    sdk: flutter         # <--- BIAR KALENDER JADI LOKAL
  cupertino_icons: ^1.0.8
  audioplayers: ^6.5.1
  scrollable_positioned_list: ^0.3.8
  url_launcher: ^6.3.1
  flutter_qiblah: ^3.2.0
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  adhan: ^2.0.0+1
  intl: ^0.20.2
  flutter_local_notifications: ^21.0.0-dev.2 # <--- KEMBALI KE STABIL BIAR GAK ERROR
  timezone: ^0.11.0
  geocoding: ^4.0.0
  shared_preferences: ^2.2.2
  upgrader: ^12.5.0
  version: ^3.0.2
  ota_update: ^7.1.0
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/yusuf.png
    - assets/images/logo_yusuf.png
    - assets/images/kabah.png
    - assets/data/
    - assets/audio/waqiah/
    - assets/audio/yasin/
    - assets/audio/adzan/
    - assets/images/compass.png
    - assets/images/qibla_needle.png

# Bagian Khusus Ikon Sultan
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_yusuf.png"
  min_sdk_android: 21
  adaptive_icon_background: "#1a1a1a"
  adaptive_icon_foreground: "assets/images/logo_yusuf.png"