name: yasin_tahlil
description: "Aplikasi Yasin Tahlil Sultan by Yusuf Ardiansyah."
publish_to: 'none'
version: 1.3.0+9

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Audio & Media
  audioplayers: ^6.5.1

  # UI & Navigation
  scrollable_positioned_list: ^0.3.8
  flutter_screenutil: ^5.9.0

  # Utils & System
  url_launcher: ^6.3.1
  permission_handler: ^12.0.1
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  version: ^3.0.2
  timezone: ^0.11.0

  # Location & Prayer Times
  flutter_qiblah: ^3.2.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  adhan: ^2.0.0+1

  # Notifications
  flutter_local_notifications: ^21.0.0-dev.2

  # Firebase & Auth
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  google_sign_in: ^7.2.0

  # Update & Maintenance
  upgrader: ^12.5.0
  ota_update: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    # Images
    - assets/images/yusuf.png
    - assets/images/logo_yusuf.png
    - assets/images/kabah.png
    - assets/images/compass.png
    - assets/images/qibla_needle.png
    # Data & Audio (Folder-based)
    - assets/data/
    - assets/audio/waqiah/
    - assets/audio/yasin/
    - assets/audio/adzan/

# Bagian Khusus Ikon Sultan
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_yusuf.png"
  min_sdk_android: 21
  adaptive_icon_background: "#1a1a1a"
  adaptive_icon_foreground: "assets/images/logo_yusuf.png"